assert = require 'assert'
{lemmas, lemmas_with_pos} = require './'

assert.deepEqual lemmas_with_pos('analyses', 'noun'), [ ["analysis", "noun"] ]

# Lemmatizer leaves alone words that its dictionary does not contain.
assert.deepEqual lemmas_with_pos('MacBooks', 'noun'), [ ['MacBooks', 'noun'] ]

# Lemmatize a word with a part of speech (pos).
assert.deepEqual lemmas_with_pos('desks', 'noun'), [ ['desk', 'noun'] ]
assert.deepEqual lemmas_with_pos('hired', 'verb'), [ ['hire', 'verb'] ]
assert.deepEqual lemmas_with_pos('worried', 'verb'), [ ['worry', 'verb'] ]
assert.deepEqual lemmas_with_pos('partying', 'verb'), [ ['party', 'verb'] ]
assert.deepEqual lemmas_with_pos('better', 'adj'),  [ ['better', 'adj'], ['good', 'adj'] ]
assert.deepEqual lemmas_with_pos('hotter', 'adj'),  [ ['hot', 'adj'] ]
assert.deepEqual lemmas_with_pos('best', 'adv'),  [ ['best', 'adv'], ['well', 'adv'] ]
assert.deepEqual lemmas_with_pos('best', 'adj'),  [ ['best', 'adj'], ['good', 'adj'] ]

# Lemmatizer give a result even when no pos is given, by assuming it to be :verb, :noun, :adv, or :adj.
assert.deepEqual lemmas_with_pos('plays'), [ ['play', 'verb'], ['play', 'noun'] ]
assert.deepEqual lemmas_with_pos('oxen'), [ ['ox', 'noun'], ['oxen', 'noun'] ]
assert.deepEqual lemmas_with_pos('fired'), [ ['fire', 'verb'], ['fired', 'adj'] ]
assert.deepEqual lemmas_with_pos('slower'), [ ['slow', 'adv'], ['slower', 'adv'], ['slow', 'adj'] ]

# non-existing word
assert.deepEqual lemmas_with_pos('asdfassda'), [ ['asdfassda', ''] ]

# various test with pos
assert.deepEqual lemmas_with_pos('goes', 'verb'), [ ['go', 'verb'] ]
assert.deepEqual lemmas_with_pos('went', 'verb'), [ ['go', 'verb'] ]
assert.deepEqual lemmas_with_pos('gone', 'verb'), [ ['go', 'verb'] ]
assert.deepEqual lemmas_with_pos('writes', 'verb'), [ ['write', 'verb'] ]
assert.deepEqual lemmas_with_pos('wrote', 'verb'), [ ['write', 'verb'] ]
assert.deepEqual lemmas_with_pos('written', 'verb'), [ ['write', 'verb'] ]
assert.deepEqual lemmas_with_pos('confirms', 'verb'), [ ['confirm', 'verb'] ]
assert.deepEqual lemmas_with_pos('confirmed', 'verb'), [ ['confirm', 'verb'] ]
assert.deepEqual lemmas_with_pos('confirming', 'verb'), [ ['confirm', 'verb'] ]
assert.deepEqual lemmas_with_pos('acidless', 'noun'), [ ['acidless', 'noun'] ]
assert.deepEqual lemmas_with_pos('pizzas', 'noun'), [ ['pizza', 'noun'] ]
assert.deepEqual lemmas_with_pos('foxes', 'noun'), [ ['fox', 'noun'] ]
assert.deepEqual lemmas_with_pos('hacked', 'verb'), [ ['hack', 'verb'] ]
assert.deepEqual lemmas_with_pos('coded', 'verb'), [ ['code', 'verb'] ]
assert.deepEqual lemmas_with_pos('fitting', 'verb'), [ ['fit', 'verb'] ]
assert.deepEqual lemmas_with_pos('coding', 'verb'), [ ['code', 'verb'] ]
assert.deepEqual lemmas_with_pos('pirouetting', 'verb'), [ ['pirouette', 'verb'] ]
assert.deepEqual lemmas_with_pos('hacking', 'verb'), [ ['hack', 'verb'] ]
assert.deepEqual lemmas_with_pos('earliest', 'adj'), [ ['earliest', 'adj'], ['early', 'adj'] ]
assert.deepEqual lemmas_with_pos('biggest', 'adj'), [ ['big', 'adj'] ]
assert.deepEqual lemmas_with_pos('largest', 'adj'), [ ['large', 'adj'] ]
assert.deepEqual lemmas_with_pos('smallest', 'adj'), [ ['small', 'adj'] ]
assert.deepEqual lemmas_with_pos('earlier', 'adj'), [ ['earlier', 'adj'], ['early', 'adj'] ]
assert.deepEqual lemmas_with_pos('bigger', 'adj'), [ ['big', 'adj'], ['bigger', 'adj'] ]
assert.deepEqual lemmas_with_pos('larger', 'adj'), [ ['large', 'adj'], ['larger', 'adj'] ]
assert.deepEqual lemmas_with_pos('smaller', 'adj'), [ ['small', 'adj'], ['smaller', 'adj'] ]
assert.deepEqual lemmas_with_pos('recognizable', 'adj'), [ ['recognizable', 'adj'] ]
assert.deepEqual lemmas_with_pos('networkable', 'adj'), [ ['networkable', 'adj'] ]
assert.deepEqual lemmas_with_pos('resettability', 'noun'), [ ['resettability', 'noun'] ]
assert.deepEqual lemmas_with_pos('repairability', 'noun'), [ ['repairability', 'noun'] ]
assert.deepEqual lemmas_with_pos('reorganizability', 'noun'), [ ['reorganizability', 'noun'] ]
assert.deepEqual lemmas_with_pos('starts', 'verb'), [ ['start', 'verb'] ]
assert.deepEqual lemmas_with_pos('teaches', 'verb'), [ ['teach', 'verb'] ]
assert.deepEqual lemmas_with_pos('talked', 'verb'), [ ['talk', 'verb'] ]
assert.deepEqual lemmas_with_pos('saved', 'verb'), [ ['save', 'verb'] ]
assert.deepEqual lemmas_with_pos('sitting', 'verb'), [ ['sit', 'verb'] ]
assert.deepEqual lemmas_with_pos('having', 'verb'), [ ['have', 'verb'] ]
assert.deepEqual lemmas_with_pos('talking', 'verb'), [ ['talk', 'verb'] ]
assert.deepEqual lemmas_with_pos('heavier', 'adj'), [ ['heavy', 'adj'] ]
assert.deepEqual lemmas_with_pos('bigger', 'adj'), [ ['big', 'adj'], ['bigger', 'adj'] ]
assert.deepEqual lemmas_with_pos('huger', 'adj'), [ ['huge', 'adj'] ]
assert.deepEqual lemmas_with_pos('lower', 'adj'), [ ['low', 'adj'] ]
assert.deepEqual lemmas_with_pos('writable', 'adj'), [ ['writable', 'adj'] ]
assert.deepEqual lemmas_with_pos('readable', 'adj'), [ ['readable', 'adj'] ]
assert.deepEqual lemmas_with_pos('readability', 'noun'), [ ['readability', 'noun'] ]
assert.deepEqual lemmas_with_pos('writability', 'noun'), [ ['writability', 'noun'] ]
assert.deepEqual lemmas_with_pos('scoreless', 'noun'), [ ['scoreless', 'noun'] ]
assert.deepEqual lemmas_with_pos('dogs', 'noun'), [ ['dog', 'noun'] ]
assert.deepEqual lemmas_with_pos('dishes', 'noun'), [ ['dish', 'noun'] ]
assert.deepEqual lemmas_with_pos('heaviest', 'adj'), [ ['heavy', 'adj'] ]
assert.deepEqual lemmas_with_pos('biggest', 'adj'), [ ['big', 'adj'] ]
assert.deepEqual lemmas_with_pos('hugest', 'adj'), [ ['huge', 'adj'] ]
assert.deepEqual lemmas_with_pos('lowest', 'adj'), [ ['low', 'adj'], ['lowest', 'adj'] ]
assert.deepEqual lemmas_with_pos('heavier', 'adj'), [ ['heavy', 'adj'] ]
assert.deepEqual lemmas_with_pos('bigger', 'adj'), [ ['big', 'adj'], ['bigger', 'adj'] ]
assert.deepEqual lemmas_with_pos('lower', 'adj'), [ ['low', 'adj'] ]
assert.deepEqual lemmas_with_pos('higher', 'adj'), [ ['high', 'adj'], ['higher', 'adj'] ]
assert.deepEqual lemmas_with_pos('leaves', 'noun'), [ ['leaf', 'noun'], ['leave', 'noun'] ]
assert.deepEqual lemmas_with_pos('player', 'noun'), [ ['player', 'noun'] ]
assert.deepEqual lemmas_with_pos('priorities', 'noun'), [ ['priority', 'noun'] ]
assert.deepEqual lemmas_with_pos('matter', 'verb'), [ ['matter', 'verb'] ]
assert.deepEqual lemmas_with_pos('matter', 'noun'), [ ['matter', 'noun'] ]
assert.deepEqual lemmas_with_pos('matter', 'adj'), [ ['mat', 'adj'], ['matt', 'adj'], ['matte', 'adj'] ]
assert.deepEqual lemmas_with_pos('added', 'verb'), [ ['add', 'verb'] ]
assert.deepEqual lemmas_with_pos('opposes', 'verb'), [ ['oppose', 'verb' ] ]
assert.deepEqual lemmas_with_pos('singing', 'verb'), [ ['sing', 'verb' ] ]
assert.deepEqual lemmas_with_pos('dying', 'verb'), [ ['die', 'verb' ] ]
assert.deepEqual lemmas_with_pos('after', 'adv'), [ ['aft', 'adv' ], ['after', 'adv' ] ]
assert.deepEqual lemmas_with_pos('us', 'noun'), [ ['us', 'noun' ] ]

# various test without pos
assert.deepEqual lemmas_with_pos('goes'), [ ['go', 'verb'], ['go', 'noun'] ]
assert.deepEqual lemmas_with_pos('went'), [ ['go', 'verb'] ]
assert.deepEqual lemmas_with_pos('gone'), [ ['go', 'verb'], ['gone', 'adj'] ]
assert.deepEqual lemmas_with_pos('writes'), [ ['write', 'verb'] ]
assert.deepEqual lemmas_with_pos('wrote'), [ ['write', 'verb'] ]
assert.deepEqual lemmas_with_pos('written'), [ ['write', 'verb'], ['written', 'adj'] ]
assert.deepEqual lemmas_with_pos('confirms'), [ ['confirm', 'verb'] ]
assert.deepEqual lemmas_with_pos('confirmed'), [ ['confirm', 'verb'], ['confirmed', 'adj'] ]
assert.deepEqual lemmas_with_pos('confirming'), [ ['confirm', 'verb'], ['confirming', 'adj'] ]
assert.deepEqual lemmas_with_pos('acidless'), [ ['acidless', ''] ]
assert.deepEqual lemmas_with_pos('pizzas'), [ ['pizza', 'noun'] ]
assert.deepEqual lemmas_with_pos('foxes'), [ ['fox', 'verb'], ['fox', 'noun'] ]
assert.deepEqual lemmas_with_pos('hacked'), [ ['hack', 'verb'] ]
assert.deepEqual lemmas_with_pos('coded'), [ ['code', 'verb'] ]
assert.deepEqual lemmas_with_pos('fitting'), [ ['fit', 'verb'], ['fitting', 'noun'], ['fitting', 'adj'] ]
assert.deepEqual lemmas_with_pos('coding'), [ ['code', 'verb'], ['coding', 'noun'] ]
assert.deepEqual lemmas_with_pos('pirouetting'), [ ['pirouette', 'verb'] ]
assert.deepEqual lemmas_with_pos('hacking'), [ ['hack', 'verb'] ]
assert.deepEqual lemmas_with_pos('earliest'), [ ['earliest', 'adv'], ['early', 'adv'], ['earliest', 'adj'], ['early', 'adj'] ]
assert.deepEqual lemmas_with_pos('biggest'), [ ['big', 'adv'], ['big', 'adj'] ]
assert.deepEqual lemmas_with_pos('largest'), [ ['large', 'adv'], ['large', 'adj'] ]
assert.deepEqual lemmas_with_pos('smallest'), [ ['small', 'adv'], ['small', 'adj'] ]
assert.deepEqual lemmas_with_pos('earlier'), [ ['earlier', 'adv'], ['early', 'adv'], ['earlier', 'adj'], ['early', 'adj'] ]
assert.deepEqual lemmas_with_pos('bigger'), [ ['big', 'adv'], ['big', 'adj'], ['bigger', 'adj'] ]
assert.deepEqual lemmas_with_pos('larger'), [ ['large', 'adv'], ['large', 'adj'], ['larger', 'adj'] ]
assert.deepEqual lemmas_with_pos('smaller'), [ ['small', 'adv'], ['small', 'adj'], ['smaller', 'adj'] ]
assert.deepEqual lemmas_with_pos('recognizable'), [ ['recognize', 'verb'], ['recognizable', 'adj'] ]
assert.deepEqual lemmas_with_pos('networkable'), [ ['network', 'verb'] ]
assert.deepEqual lemmas_with_pos('resettability'), [ ['reset', 'verb'] ]
assert.deepEqual lemmas_with_pos('repairability'), [ ['repair', 'verb'] ]
assert.deepEqual lemmas_with_pos('reorganizability'), [ ['reorganize', 'verb'] ]
assert.deepEqual lemmas_with_pos('starts'), [ ['start', 'verb'], ['start', 'noun'] ]
assert.deepEqual lemmas_with_pos('teaches'), [ ['teach', 'verb'], ['teach', 'noun'] ]
assert.deepEqual lemmas_with_pos('talked'), [ ['talk', 'verb'] ]
assert.deepEqual lemmas_with_pos('saved'), [ ['save', 'verb'], ['saved', 'adj'] ]
assert.deepEqual lemmas_with_pos('sitting'), [ ['sit', 'verb'], ['sitting', 'noun'], ['sitting', 'adj'] ]
assert.deepEqual lemmas_with_pos('having'), [ ['have', 'verb'] ]
assert.deepEqual lemmas_with_pos('talking'), [ ['talk', 'verb'], ['talking', 'noun'] ]
assert.deepEqual lemmas_with_pos('heavier'), [ ['heavy', 'adv'], ['heavy', 'adj'] ]
assert.deepEqual lemmas_with_pos('bigger'), [ ['big', 'adv'], ['big', 'adj'], ['bigger', 'adj'] ]
assert.deepEqual lemmas_with_pos('huger'), [ ['huge', 'adj'] ]
assert.deepEqual lemmas_with_pos('lower'), [ ['lower', 'verb'], ['lower', 'noun'], ['low', 'adv'], ['low', 'adj'] ]
assert.deepEqual lemmas_with_pos('writable'), [ ['write', 'verb'] ]
assert.deepEqual lemmas_with_pos('readable'), [ ['read', 'verb'], ['readable', 'adj'] ]
assert.deepEqual lemmas_with_pos('resettable'), [ ['reset', 'verb'] ]
assert.deepEqual lemmas_with_pos('readability'), [ ['read', 'verb'], ['readability', 'noun'] ]
assert.deepEqual lemmas_with_pos('writability'), [ ['write', 'verb'] ]
assert.deepEqual lemmas_with_pos('scoreless'), [ ['scoreless', 'adj'] ]
assert.deepEqual lemmas_with_pos('dogs'), [ ['dog', 'verb'], ['dog', 'noun'] ]
assert.deepEqual lemmas_with_pos('dishes'), [ ['dish', 'verb'], ['dish', 'noun'] ]
assert.deepEqual lemmas_with_pos('heaviest'), [ ['heavy', 'adv'], ['heavy', 'adj'] ]
assert.deepEqual lemmas_with_pos('biggest'), [ ['big', 'adv'], ['big', 'adj'] ]
assert.deepEqual lemmas_with_pos('hugest'), [ ['huge', 'adj'] ]
assert.deepEqual lemmas_with_pos('lowest'), [ ['low', 'adv'], ['lowest', 'adv'], ['low', 'adj'], ['lowest', 'adj'] ]
assert.deepEqual lemmas_with_pos('heavier'), [ ['heavy', 'adv'], ['heavy', 'adj'] ]
assert.deepEqual lemmas_with_pos('bigger'), [ ['big', 'adv'], ['big', 'adj'], ['bigger', 'adj'] ]
assert.deepEqual lemmas_with_pos('lower'), [ ['lower', 'verb'], ['lower', 'noun'], ['low', 'adv'], ['low', 'adj'] ]
assert.deepEqual lemmas_with_pos('higher'), [ ['high', 'adv'], ['high', 'adj'], ['higher', 'adj'] ]
assert.deepEqual lemmas_with_pos('leaves'), [ ['leave', 'verb'], ['leaf', 'noun'], ['leave', 'noun'] ]
assert.deepEqual lemmas_with_pos('player'), [ ['player', 'noun'] ]
assert.deepEqual lemmas_with_pos('priorities'), [ ['priority', 'noun'] ]
assert.deepEqual lemmas_with_pos('matter'), [ ['matter', 'verb'], ['matter', 'noun'], ['mat', 'adj'], ['matt', 'adj'], ['matte', 'adj'] ]
assert.deepEqual lemmas_with_pos('added'), [ ['add', 'verb'] ]
assert.deepEqual lemmas_with_pos('opposes'), [ ['oppose', 'verb' ] ]
assert.deepEqual lemmas_with_pos('singing'), [ ['sing', 'verb'], ['singing', 'noun'], ['singing', 'adj'] ]
assert.deepEqual lemmas_with_pos('dying'), [ ['die', 'verb'], ['dying', 'noun'], ['dying', 'adj'] ]
assert.deepEqual lemmas_with_pos('after'), [ ['aft', 'adv' ], ['after', 'adv'], ['aft', 'adj' ], ['after', 'adj'] ]
assert.deepEqual lemmas_with_pos('us'), [ ['us', 'noun' ] ]

# only_lemmas tests
assert.deepEqual lemmas('analyses', 'noun'), [ 'analysis' ]

# Lemmatizer leaves alone words that its dictionary does not contain.
assert.deepEqual lemmas('MacBooks', 'noun'), [ 'MacBooks' ]

# Lemmatize a word with a part of speech (pos).
assert.deepEqual lemmas('desks', 'noun'), [ 'desk' ]
assert.deepEqual lemmas('hired', 'verb'), [ 'hire' ]
assert.deepEqual lemmas('worried', 'verb'), [ 'worry' ]
assert.deepEqual lemmas('partying', 'verb'), [ 'party' ]
assert.deepEqual lemmas('better', 'adj'), ['better', 'good']
assert.deepEqual lemmas('hotter', 'adj'), ['hot'] 
assert.deepEqual lemmas('best', 'adv'), ['best', 'well']
assert.deepEqual lemmas('best', 'adj'), ['best', 'good']

# Lemmatizer give a result even when no pos is given, by assuming it to be :verb, :noun, :adv, or :adj.
assert.deepEqual lemmas('plays'), [ 'play' ]
assert.deepEqual lemmas('oxen'), [ 'ox', 'oxen' ]
assert.deepEqual lemmas('fired'), [ 'fire', 'fired' ]
assert.deepEqual lemmas('slower'), [ 'slow', 'slower' ]

# non-existing word
assert.deepEqual lemmas('asdfassda'), [ 'asdfassda' ]

# various test with pos
assert.deepEqual lemmas('goes', 'verb'), [ 'go' ]
assert.deepEqual lemmas('went', 'verb'), [ 'go' ]
assert.deepEqual lemmas('gone', 'verb'), [ 'go' ]
assert.deepEqual lemmas('writes', 'verb'), [ 'write' ]
assert.deepEqual lemmas('wrote', 'verb'), [ 'write' ]
assert.deepEqual lemmas('written', 'verb'), [ 'write' ]
assert.deepEqual lemmas('confirms', 'verb'), [ 'confirm' ]
assert.deepEqual lemmas('confirmed', 'verb'), [ 'confirm' ]
assert.deepEqual lemmas('confirming', 'verb'), [ 'confirm' ]
assert.deepEqual lemmas('acidless', 'noun'), [ 'acidless' ]
assert.deepEqual lemmas('pizzas', 'noun'), [ 'pizza' ]
assert.deepEqual lemmas('foxes', 'noun'), [ 'fox' ]
assert.deepEqual lemmas('hacked', 'verb'), [ 'hack' ]
assert.deepEqual lemmas('coded', 'verb'), [ 'code' ]
assert.deepEqual lemmas('fitting', 'verb'), [ 'fit' ]
assert.deepEqual lemmas('coding', 'verb'), [ 'code' ]
assert.deepEqual lemmas('pirouetting', 'verb'), [ 'pirouette' ]
assert.deepEqual lemmas('hacking', 'verb'), [ 'hack' ]
assert.deepEqual lemmas('earliest', 'adj'), [ 'earliest', 'early' ]
assert.deepEqual lemmas('biggest', 'adj'), [ 'big' ]
assert.deepEqual lemmas('largest', 'adj'), [ 'large' ]
assert.deepEqual lemmas('smallest', 'adj'), [ 'small' ]
assert.deepEqual lemmas('earlier', 'adj'), [ 'earlier', 'early' ]
assert.deepEqual lemmas('bigger', 'adj'), [ 'big', 'bigger' ]
assert.deepEqual lemmas('larger', 'adj'), [ 'large', 'larger' ]
assert.deepEqual lemmas('smaller', 'adj'), [ 'small', 'smaller' ]
assert.deepEqual lemmas('recognizable', 'adj'), [ 'recognizable' ]
assert.deepEqual lemmas('networkable', 'adj'), [ 'networkable' ]
assert.deepEqual lemmas('resettability', 'noun'), [ 'resettability' ]
assert.deepEqual lemmas('repairability', 'noun'), [ 'repairability' ]
assert.deepEqual lemmas('reorganizability', 'noun'), [ 'reorganizability' ]
assert.deepEqual lemmas('starts', 'verb'), [ 'start' ]
assert.deepEqual lemmas('teaches', 'verb'), [ 'teach' ]
assert.deepEqual lemmas('talked', 'verb'), [ 'talk' ]
assert.deepEqual lemmas('saved', 'verb'), [ 'save' ]
assert.deepEqual lemmas('sitting', 'verb'), [ 'sit' ]
assert.deepEqual lemmas('having', 'verb'), [ 'have' ]
assert.deepEqual lemmas('talking', 'verb'), [ 'talk' ]
assert.deepEqual lemmas('heavier', 'adj'), [ 'heavy' ]
assert.deepEqual lemmas('bigger', 'adj'), [ 'big', 'bigger' ]
assert.deepEqual lemmas('huger', 'adj'), [ 'huge' ]
assert.deepEqual lemmas('lower', 'adj'), [ 'low' ]
assert.deepEqual lemmas('writable', 'adj'), [ 'writable' ]
assert.deepEqual lemmas('readable', 'adj'), [ 'readable' ]
assert.deepEqual lemmas('readability', 'noun'), [ 'readability' ]
assert.deepEqual lemmas('writability', 'noun'), [ 'writability' ]
assert.deepEqual lemmas('scoreless', 'noun'), [ 'scoreless' ]
assert.deepEqual lemmas('dogs', 'noun'), [ 'dog' ]
assert.deepEqual lemmas('dishes', 'noun'), [ 'dish' ]
assert.deepEqual lemmas('heaviest', 'adj'), [ 'heavy' ]
assert.deepEqual lemmas('biggest', 'adj'), [ 'big' ]
assert.deepEqual lemmas('hugest', 'adj'), [ 'huge' ]
assert.deepEqual lemmas('lowest', 'adj'), [ 'low', 'lowest' ]
assert.deepEqual lemmas('heavier', 'adj'), [ 'heavy' ]
assert.deepEqual lemmas('bigger', 'adj'), [ 'big', 'bigger' ]
assert.deepEqual lemmas('lower', 'adj'), [ 'low' ]
assert.deepEqual lemmas('higher', 'adj'), [ 'high', 'higher' ]
assert.deepEqual lemmas('leaves', 'noun'), [ 'leaf', 'leave' ]
assert.deepEqual lemmas('player', 'noun'), [ 'player' ]
assert.deepEqual lemmas('priorities', 'noun'), [ 'priority' ]
assert.deepEqual lemmas('matter', 'verb'), [ 'matter' ]
assert.deepEqual lemmas('matter', 'noun'), [ 'matter' ]
assert.deepEqual lemmas('matter', 'adj'), [ 'mat', 'matt', 'matte' ]
assert.deepEqual lemmas('added', 'verb'), [ 'add' ]
assert.deepEqual lemmas('opposes', 'verb'), [ 'oppose' ]
assert.deepEqual lemmas('singing', 'verb'), [ 'sing' ]
assert.deepEqual lemmas('dying', 'verb'), [ 'die' ]
assert.deepEqual lemmas('after', 'adv'), [ 'aft', 'after' ]
assert.deepEqual lemmas('us', 'noun'), [ 'us' ]

# various test without pos
assert.deepEqual lemmas('goes'), [ 'go' ]
assert.deepEqual lemmas('went'), [ 'go' ]
assert.deepEqual lemmas('gone'), [ 'go', 'gone' ]
assert.deepEqual lemmas('writes'), [ 'write' ]
assert.deepEqual lemmas('wrote'), [ 'write' ]
assert.deepEqual lemmas('written'), [ 'write', 'written' ]
assert.deepEqual lemmas('confirms'), [ 'confirm' ]
assert.deepEqual lemmas('confirmed'), [ 'confirm', 'confirmed' ]
assert.deepEqual lemmas('confirming'), [ 'confirm', 'confirming' ]
assert.deepEqual lemmas('acidless'), [ 'acidless' ]
assert.deepEqual lemmas('pizzas'), [ 'pizza' ]
assert.deepEqual lemmas('foxes'), [ 'fox' ]
assert.deepEqual lemmas('hacked'), [ 'hack' ]
assert.deepEqual lemmas('coded'), [ 'code' ]
assert.deepEqual lemmas('fitting'), [ 'fit', 'fitting' ]
assert.deepEqual lemmas('coding'), [ 'code', 'coding' ]
assert.deepEqual lemmas('pirouetting'), [ 'pirouette' ]
assert.deepEqual lemmas('hacking'), [ 'hack' ]
assert.deepEqual lemmas('earliest'), [ 'earliest', 'early' ]
assert.deepEqual lemmas('biggest'), [ 'big' ]
assert.deepEqual lemmas('largest'), [ 'large' ]
assert.deepEqual lemmas('smallest'), [ 'small' ]
assert.deepEqual lemmas('earlier'), [ 'earlier', 'early' ]
assert.deepEqual lemmas('bigger'), [ 'big', 'bigger' ]
assert.deepEqual lemmas('larger'), [ 'large', 'larger' ]
assert.deepEqual lemmas('smaller'), [ 'small', 'smaller' ]
assert.deepEqual lemmas('recognizable'), [ 'recognize', 'recognizable' ]
assert.deepEqual lemmas('networkable'), [ 'network' ]
assert.deepEqual lemmas('resettability'), [ 'reset' ]
assert.deepEqual lemmas('repairability'), [ 'repair' ]
assert.deepEqual lemmas('reorganizability'), [ 'reorganize' ]
assert.deepEqual lemmas('starts'), [ 'start' ]
assert.deepEqual lemmas('teaches'), [ 'teach' ]
assert.deepEqual lemmas('talked'), [ 'talk' ]
assert.deepEqual lemmas('saved'), [ 'save', 'saved' ]
assert.deepEqual lemmas('sitting'), [ 'sit', 'sitting' ]
assert.deepEqual lemmas('having'), [ 'have' ]
assert.deepEqual lemmas('talking'), [ 'talk', 'talking' ]
assert.deepEqual lemmas('heavier'), [ 'heavy' ]
assert.deepEqual lemmas('bigger'), [ 'big', 'bigger' ]
assert.deepEqual lemmas('huger'), [ 'huge' ]
assert.deepEqual lemmas('lower'), [ 'lower', 'low' ]
assert.deepEqual lemmas('writable'), [ 'write' ]
assert.deepEqual lemmas('readable'), [ 'read', 'readable' ]
assert.deepEqual lemmas('resettable'), [ 'reset' ]
assert.deepEqual lemmas('readability'), [ 'read', 'readability' ]
assert.deepEqual lemmas('writability'), [ 'write' ]
assert.deepEqual lemmas('scoreless'), [ 'scoreless' ]
assert.deepEqual lemmas('dogs'), [ 'dog' ]
assert.deepEqual lemmas('dishes'), [ 'dish' ]
assert.deepEqual lemmas('heaviest'), [ 'heavy' ]
assert.deepEqual lemmas('biggest'), [ 'big' ]
assert.deepEqual lemmas('hugest'), [ 'huge' ]
assert.deepEqual lemmas('lowest'), [ 'low', 'lowest' ]
assert.deepEqual lemmas('heavier'), [ 'heavy' ]
assert.deepEqual lemmas('bigger'), [ 'big', 'bigger' ]
assert.deepEqual lemmas('lower'), [ 'lower', 'low' ]
assert.deepEqual lemmas('higher'), [ 'high', 'higher' ]
assert.deepEqual lemmas('leaves'), [ 'leave', 'leaf' ]
assert.deepEqual lemmas('player'), [ 'player' ]
assert.deepEqual lemmas('priorities'), [ 'priority' ]
assert.deepEqual lemmas('matter'), ["matter","mat","matt","matte"]
assert.deepEqual lemmas('added'), [ 'add' ]
assert.deepEqual lemmas('opposes'), [ 'oppose' ]
assert.deepEqual lemmas('singing'), [ 'sing', 'singing' ]
assert.deepEqual lemmas('dying'), [ 'die', 'dying' ]
assert.deepEqual lemmas('after'), [ 'aft', 'after' ]
assert.deepEqual lemmas('us'), [ 'us' ]
